import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./style-email.css";
import "./themee5ca.css";
import "./dashlitee5ca.css";
import { Sidebar } from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className="nk-body ui-rounder npc-default has-sidebar no-touch nk-nio-theme">
        <div className="nk-app-root">
          <Sidebar/>
          <div className="nk-main">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
